import type { DemolayOrganization } from "@/lib/demolay/organizations";

/** Capítulos DeMolay de Mato Grosso (cadastro ADAE-MT). */
export const DEMOLAY_CHAPTERS_MT: DemolayOrganization[] = [
  { number: 67, name: "Rondonópolis", city: "Rondonópolis" },
  { number: 103, name: "Cuiabá", city: "Cuiabá" },
  { number: 106, name: "Marechal Rondon", city: "Cuiabá" },
  { number: 107, name: "Guiratinguense", city: "Guiratinga" },
  { number: 205, name: "Cavaleiros de Um Novo Tempo", city: "Cuiabá" },
  { number: 267, name: "Jaciara", city: "Jaciara" },
  { number: 308, name: "Alexandre Carlos Pierre", city: "Cáceres" },
  { number: 309, name: "Ronan Borges Alves", city: "Mirassol d'Oeste" },
  { number: 336, name: "Tangará", city: "Tangará da Serra" },
  { number: 344, name: "Sorriso", city: "Sorriso" },
  { number: 348, name: "Cavaleiros da Era de Aquarius", city: "Barra do Garças" },
  { number: 362, name: "Sol Nascente", city: "Cuiabá" },
  { number: 409, name: "Várzea Grande", city: "Várzea Grande" },
  { number: 446, name: "Alto Araguaia", city: "Alto Araguaia" },
  { number: 458, name: "Alta Floresta", city: "Alta Floresta" },
  { number: 510, name: "Sinop", city: "Sinop" },
  { number: 532, name: "XVIII de Março", city: "Cuiabá" },
  { number: 538, name: "Primavera do Leste", city: "Primavera do Leste" },
  { number: 551, name: "Fraternidade Juinense", city: "Juína" },
  { number: 570, name: "Vale do Teles Pires", city: "Colíder" },
  { number: 574, name: "Juventude da Acácia Cuiabana", city: "Cuiabá" },
  { number: 577, name: "Guardiões da Aliança", city: "Diamantino" },
  { number: 587, name: "Guardiões do Templo de Salomão", city: "Cuiabá" },
  { number: 632, name: "Cavaleiros da Pedra Angular", city: "Primavera do Leste" },
  { number: 633, name: "Sagrados Cavaleiros de Fênix", city: "Barra do Bugres" },
  { number: 637, name: "Everaldo Vicente Pereira", city: "Rondonópolis" },
  {
    number: 638,
    name: "Pedro Henrique Santana de Oliveira",
    city: "São José dos Quatro Marcos",
  },
  { number: 641, name: "Guardiões da Serra do Roncador", city: "Água Boa" },
  { number: 652, name: "Conquista e Integração", city: "Cuiabá" },
  { number: 743, name: "Cavaleiros da Fraternidade", city: "Campo Verde" },
  { number: 746, name: "Cavaleiros da Paz", city: "Nova Xavantina" },
  { number: 766, name: "Canarana", city: "Canarana" },
  { number: 812, name: "Cavaleiros do Alto Xingú", city: "Querência" },
  { number: 862, name: "Cavaleiros do Guaporé", city: "Pontes e Lacerda" },
  { number: 928, name: "União Fraternal Parecis", city: "Campo Novo do Parecis" },
  { number: 954, name: "8 de Abril", city: "Cuiabá" },
  { number: 998, name: "Estrela de Davi", city: "Sapezal" },
  { number: 1090, name: "União das Luzes", city: "Lucas do Rio Verde" },
  { number: 1129, name: "Acácia do Arinos", city: "Nova Mutum" },
  { number: 1155, name: "Sentinela Cuiabana", city: "Cuiabá" },
  { number: 1187, name: "Constelação dos Magos", city: "Juína" },
  {
    number: 1215,
    name: "Cavaleiros da Juventude do Norte Araguaia",
    city: "Porto Alegre do Norte",
  },
  { number: 1216, name: "Antônio dos Reis Rodrigues", city: "Poxoréu" },
  { number: 1238, name: "Henrique José de Souza", city: "Cuiabá" },
  { number: 1261, name: "Cavaleiros de Fênix", city: "Barra do Bugres" },
];
